### ISSUE TITLE
set_attributes_config() & set_attributes_value() should do a PUT instead of POST

### ISSUE THREAD

**Issue by TheBazeman** [goooroooX/ZipatoPy#1]
Hi,

Took me a couple of hours but figured it out when wanted to set a value to a device. The {"value" : "<value>"} json is not sent along to the Zipabox when doing a POST. Changed it to a PUT and it works offcourse. Can you change the code?

I have tested it with set_attributes_value() and I am assuming it should be changed on set_attributes_config() too, so please verify.

Thanks a lot and keep up the good work,

Kind regards and have a nice weekend, -Bas

PS: Local API does return the Attribute name but you should use ["attributeName"] instead of ["name"], maybe you want to have a look to that also.

**Comment by goooroooX** [comment]
Thank you for information, I'll update code.

**Comment by goooroooX** [comment]
fixed.
