### ISSUE TITLE
Can you add the following function to your code?

### ISSUE THREAD

**Issue by TheBazeman** [goooroooX/ZipatoPy#3]
Hi there again, I would like to get the battery percentage of devices. Can't do that with the current set. Can you add the following to your code?

class ZipatoPy(BaseAPIClient):

    def get_device_status(self, uuid):
        endpoint = "devices/" + uuid + "/status"
        return self.call_api(endpoint, "GET")

Thank,
Bas

**Comment by goooroooX** [comment]
Hi! Have you tested this code?

**Comment by TheBazeman** [comment]
Hi Dmitry,

Yes of course! You can use it with this function:

def ReadZipatoDeviceStatus(ZipatoAttributeUUID,ZipatoDeviceName):
    try:
        ZipatoDeviceValue=api.get_device_status(ZipatoAttributeUUID)["state"]
    except:
        ZipatoDeviceValue = "PROBLEM_READING_OUT_VALUE"
    return ZipatoDeviceValue


Kind regards,

Bas Bahlmann/Netherlands

Van: Dmitry [mailto:notifications@github.com]
Verzonden: woensdag 4 september 2019 16:43
Aan: goooroooX/ZipatoPy <ZipatoPy@noreply.github.com>
CC: Bas Bahlmann <bas@bahlmann.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [goooroooX/ZipatoPy] Can you add the following function to your code? (#3)


Hi! Have you tested this code?

**Comment by goooroooX** [comment]
Code updated and uploaded to pypi.
