### ISSUE TITLE
include get_device_config to your code

### ISSUE THREAD

**Issue by TheBazeman** [goooroooX/ZipatoPy#5]
Hi, Can you add something to your code?

    def get_device_config(self, uuid):
        endpoint = "devices/" + uuid + "/config"
        return self.call_api(endpoint, "GET")

right below the "def get_device_status(self, uuid):" section

Tested and working. Need this to find ghost associations created by the Fibaro RGWB modules themselves.

Thanks a lot again,
Bas

**Comment by goooroooX** [comment]
Hi! Will do early next week, Sorry for delayed response.

**Comment by goooroooX** [comment]
Code updated.
